### PR TITLE
Error in get call for table alicloud_ecs_image closes #314

### LINKED ISSUE #314: Error in get call for table `alicloud_ecs_image`
**Describe the bug**
```sql
> select * from alicloud_ecs_image where image_id = 'ubuntu_22_04_x64_20G_alibase_20221130.vhd'

Error: get call returned 2 results - the key column is not globally unique (SQLSTATE HV000)

+------+----------+-----+------+--------+-------------------+--------------+---------------+-------------+--------------+---------------+-----------+-------->
| name | image_id | arn | size | status | image_owner_alias | architecture | creation_time | description | image_family | image_version | is_copied | is_self>
+------+----------+-----+------+--------+-------------------+--------------+---------------+-------------+--------------+---------------+-----------+-------->
+------+----------+-----+------+--------+-------------------+--------------+---------------+-------------+--------------+---------------+-----------+-------->
```

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
N/A
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select name, image_id, size, status, image_owner_alias, architecture from alicloud_ecs_image where image_id = 'centos_7_9_x64_20G_alibase_20221129.vhd' and region = 'us-east-1'
+-----------------------------------------+-----------------------------------------+------+-----------+-------------------+--------------+
| name                                    | image_id                                | size | status    | image_owner_alias | architecture |
+-----------------------------------------+-----------------------------------------+------+-----------+-------------------+--------------+
| centos_7_9_x64_20G_alibase_20221129.vhd | centos_7_9_x64_20G_alibase_20221129.vhd | 20   | Available | system            | x86_64       |
+-----------------------------------------+-----------------------------------------+------+-----------+-------------------+--------------+
```
</details>

### CODE REVIEW

File: alicloud/table_alicloud_ecs_image.go [hunk 1]
```diff
@@ -22,7 +22,8 @@ func tableAlicloudEcsImage(ctx context.Context) *plugin.Table {
 			Hydrate: listEcsImages,
```
Comment (karanpopat) [inline alicloud/table_alicloud_ecs_image.go:22]: Should we include `image_id` in the List key columns for optimization since Get is now having both `image_id` and `region`?

**Comment by karanpopat** [comment]
Will this break if there is an aggregator configuration? Which might return multiple rows for multiple accounts even with a region specified.

**Comment by misraved** [comment]
@ParthaI could you please update the table docs to reflect the qual changes?

Table description update:

```
An ECS image stores information that is required to create an ECS instance. An image works as a copy that stores data from one or more disks. An ECS instance image may store data from a system disk or from both system and data disks.

To query a specific ECS image you need to pass `image_id` and `region` in the where clause (`where iamge_id='' and region=''`).
```

We could also add an example query wherein we are fetching the details of a specific image by specifying the `image_id` and `region`.

**Review by misraved — APPROVED** [review]
